version: "3.8"

services:
  nextjs-catalog:
    image: docker.io/mraldirs1231/nextjs-catalog:latest
    container_name: nextjs-catalog
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - ODOO_BASE_URL=${ODOO_BASE_URL}
      - NEXT_PUBLIC_ODOO_BASE_URL=${NEXT_PUBLIC_ODOO_BASE_URL}
      - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
      - REVALIDATE_SECRET=${REVALIDATE_SECRET}
    env_file:
      - .env
    networks:
      - nextjs-network

networks:
  nextjs-network:
    driver: bridge
